<?php
/**Статичный класс с запрещенными выражениями в,
 * водиммых пользователем, данных.
 * Список только из символов нижнего регистра
 */

class U_List_prohibited_expressions
{
	const expressions = [
		//region Команды БД

		"create database",
		"create table",
		"create view",
		"create function",
		"create procedure",
		"create trigger",
		"create user",
		"create role",
		"describe",
		"alter table",
		"truncate table",
		"drop database",
		"drop table",
		"drop view",
		"insert into",
		"delete",
		"update",
		"select",
		"union",
		"set ",
		"show ",
		"processlist",
		"where ",
		"order by",
		//endregion

		//region Команды системы
		"ls ",
		"cat ",
		"cd ",
		"pwd ",
		"mkdir ",
		"file ",
		"cp ",
		"mv ",
		"rm ",
		"ln ",
		"chmod ",
		"chown ",
		"find ",
		"locate ",
		"du ",
		"df ",
		"dd ",
		"mount ",
		"umount ",
		"more ",
		"less ",
		"head ",
		"tail ",
		"grep ",
		"sort ",
		"wc ",
		"diff ",
		"kill ",
		"xkill ",
		"pkill ",
		"killall ",
		"ps ",
		"pgrep ",
		"top ",
		"htop ",
		"time ",
		"su ",
		"sudo ",
		"date ",
		"alias ",
		"uname ",
		"uptime ",
		"sleep ",
		"useradd ",
		"userdel ",
		"usermod ",
		"passwd ",
		"man ",
		"whatis ",
		"ip ",
		"ping ",
		"nethogs ",
		"traceroute ",
		"hostname ",
		"whoami ",
		"time ",
		"who ",
		"rwho -a ",
		"finger ",
		"ps a ",
		"top ",
		"uname ",
		"free ",
		"df -h ",
		"du -bh ",
		"du -more ",
		"cat /proc/cpuinfo",
		"cat /proc/interrupts",
		"cat /proc/version",
		"cat /proc/filesystems",
		"lsmod ",
		"set|more ",
		'echo $PATH ',

		//Работа с сетью
		"netconf ",
		"route -n",
		"ipfwadm -F -p m",
		"ifconfig",
		"ifup eth0",
		"ifup ppp0",
		"ifdown ",

		//Простейшие действия
		"ls ",
		"mcopy ",
		"ln -s ",
		"rmdir ",
		"pico ",
		"lynx ",
		"tar -zxvf",
		"pine ",
		"telnet ",
		"minicom ",
		"startx ",
		"xterm ",
		"xboing ",

		//Основные Команды Администрирования
		"printtool ",
		"setup ",
		"adduser ",
		"ls -l ",
		//Контроль процессов
		"fg ",
		"bg ",
		"lpc ",
		"lpq ",
		"lprm ",
		"nice ",
		"renice  ",
		//endregion

		//region Команды PHP
		'argv',
		'argc',
		'gateway_interface',
		'server_addr',
		'server_name',
		'server_software',
		'server_protocol',
		'request_method',
		'request_time',
		'request_time_float',
		'query_string',
		'document_root',
		'http_accept',
		'http_accept_charset',
		'http_accept_encoding',
		'http_accept_language',
		'http_connection',
		'http_host',
		'http_referer',
		'http_user_agent',
		'https',
		'remote_addr',
		'remote_host',
		'remote_port',
		'remote_user',
		'redirect_remote_user',
		'script_filename',
		'server_admin',
		'server_port',
		'server_signature',
		'path_translated',
		'script_name',
		'request_uri',
		'php_auth_digest',
		'php_auth_user',
		'php_auth_pw',
		'auth_type',
		'path_info',
		'orig_path_info',
		//endregion

	];

}